conf: Fix failure of list suites option
For just listing of test suites op-test fails with unknown BMC exception.

./op-test --list-suites
Traceback (most recent call last):
  File "./op-test", line 102, in <module>
    OpTestConfiguration.conf.objs()
  File "/home/~/fixes/op-test-framework/OpTestConfiguration.py", line 365, in objs
    raise Exception("Unsupported BMC Type")
Exception: Unsupported BMC Type

list suites task is to just list the suites, so it takes the high
priority, so this patch fixes this issue.

Signed-off-by: Pridhiviraj Paidipeddi <ppaidipe@linux.vnet.ibm.com>