Fix IndexError: list index out of range issue
In case of any LAPR key does not have value op-test error out as

ERROR: runTest (testcases.HelloWorld.HelloWorld)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/op-test/testcases/HelloWorld.py", line 44, in runTest
    exist_cfg = self.cv_HMC.get_lpar_cfg()
  File "/home/op-test/common/OpTestHMC.py", line 309, in get_lpar_cfg
    value = data[1]
IndexError: list index out of range

as this fix populate that value as null string

Signed-off-by: Praveen K Pandey <praveen@linux.vnet.ibm.com>