Fixed regression issue in Flow
LOG:
======================================================================
ERROR: runTest (testcases.MachineConfig.MachineConfig)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/op-test/testcases/MachineConfig.py", line 88, in runTest
    status=LparConfig(self.cv_HMC,self.system_name,self.lpar_name,self.lpar_prof,self.machine_config['lpar'],sb_enable=self.sb_enable).LparSetup()
  File "/home/op-test/testcases/MachineConfig.py", line 264, in LparSetup
    try: self.pmem_name = conf.args.pmem_name
UnboundLocalError: local variable 'conf' referenced before assignment

----------------------------------------------------------------------
Ran 1 test in 7.324s

in case vtpm and vpmem conf varaible not defined , while calling flow requested setting to change it
made script error out, this patch address the issue

Signed-off-by: Praveen K Pandey <praveen@linux.vnet.ibm.com>