OpTestKernelDump: Fix console monitoring to use HMCConsole.connect()
Problem:
- monitor_console_thread() was calling hmc_obj.connect() directly
- OpTestHMC doesn't have connect() method
- Error: 'OpTestHMC' object has no attribute 'connect'

Solution:
- Use hmc_obj.get_host_console() to get HMCConsole object
- Call connect() on the HMCConsole object
- HMCConsole.connect() properly opens mkvterm connection

This fixes the console monitoring thread to properly establish
the console connection for capturing boot messages.

Signed-off-by: Praveen K Pandey <praveen@linux.vnet.ibm.com>