Fixup python3: handle kickstart file read/write
Let's fix below errors by reading and writing with
proper decode/encode.

File "/home/bala/op-test-framework/common/OpTestInstallUtil.py", line 548, in do_GET
    self.wfile.write(ps)
File "/usr/lib64/python3.6/socketserver.py", line 803, in write
    self._sock.sendall(b)
TypeError: a bytes-like object is required, not 'str'
---
File "/home/bala/op-test-framework/common/OpTestInstallUtil.py", line 527, in do_GET
    ps = d.format(REPO, PROXY, PASSWORD, DISK, DISK, DISK).encode()
AttributeError: 'bytes' object has no attribute 'format'

Reported-by: Balamuruhan S <bala24@linux.ibm.com>
Signed-off-by: Balamuruhan S <bala24@linux.ibm.com>
Signed-off-by: Satheesh Rajendran <sathnaga@linux.vnet.ibm.com>