Fix IndentationError caused by commit e617ed1
The Commit e617ed1 causes Indentation Error:
IndentationError: unindent does not match any outer indentation level

This Patch fixes the above error.

Signed-off-by: Misbah Anjum N <misanjumn@ibm.com>