OpTestSOL: remove the argument `logger` passed to get_console()
get_console() of OpTestSSH.py, doesn't have the `logger` argument
and we would hit,

TypeError: get_console() got an unexpected keyword argument \'logger\'\n')

Signed-off-by: Balamuruhan S <bala24@linux.vnet.ibm.com>