Fixup: Add custom logger support for ssh connection
OpenBMC systems use ssh for console access, So we will hit
with below issue, let's extend custom logger support
to ssh connection to fix this issue.

  File "./op-test-framework/testcases/RunHostTest.py", line 51, in setUp
    self.console_thread = OpSOLMonitorThread(1, "console")
  File "./op-test-framework/common/OpTestSOL.py", line 62, in __init__
    self.c = self.system.console.get_console(logger=self.logger)
TypeError: get_console() got an unexpected keyword argument 'logger'

Signed-off-by: Balamuruhan S <bala24@linux.vnet.ibm.com>
Signed-off-by: Satheesh Rajendran <sathnaga@linux.vnet.ibm.com>