Fail early if secondary config doesn't exists
Presently if the secondary config (specified via --config arg) doesn't
exist a very misleading and confusing error message is shown:

======================================================================
ERROR: runTest (testcases.OpTestFlash.OpalLidsFLASH)
----------------------------------------------------------------------
Traceback (most recent call last):
<snip>
    raise SSHSessionDisconnected("SSH session exited early!")
SSHSessionDisconnected: SSH session/console disconnected due to 'SSH session exited early!'

This is due to SafeConfigParser.read() function that doesn't report an
error in case the input file-path doesn't exists. This patch fixes this
by adding a existence check for secondary config so that a more
relevant error is reported to the user.

Signed-off-by: Vaibhav Jain <vaibhav@linux.ibm.com>