Fixed issue in installation when user miss host user name installation script error out , so this patch made some param as required
failed LOG:

======================================================================
ERROR [1174.995s]: runTest (testcases.InstallRhel.InstallRhel)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/praveen/op-test-framework/testcases/InstallRhel.py", line 120, in runTest
    self.system.host_console_login()
  File "/home/praveen/op-test-framework/common/OpTestSystem.py", line 294, in host_console_login
    l_con.sendline(l_user)
  File "/usr/lib/python2.7/site-packages/pexpect/__init__.py", line 1036, in sendline
    n = self.send(s)
  File "/usr/lib/python2.7/site-packages/pexpect/__init__.py", line 1024, in send
    s = self._coerce_send_string(s)
  File "/usr/lib/python2.7/site-packages/pexpect/__init__.py", line 496, in _coerce_send_string
    return s.encode('utf-8')
AttributeError: 'NoneType' object has no attribute 'encode'

----------------------------------------------------------------------
Ran 1 test in 1174.995s

FAILED (errors=1)

Signed-off-by: Praveen K Pandey <praveen@linux.vnet.ibm.com>