Fix OCC tests for FSP machines
Use .get() rather than [] to look in dictionary so that we don't require
ipmi user name.

16:33:58 :: Running command: op-ci-bmc-run  "op_ci_bmc.test_init()"
/home/stewart/op-test-framework/ci/source/op_ci_tools.cfg
/home/stewart/op-test-framework/ci/source/op_ci_tools.cfg
Traceback (most recent call last):
  File "<string>", line 10, in <module>
  File "/home/stewart/op-test-framework/ci/source/op_occ_fvt.py", line 66, in <m
odule>
    bmcCfg['usernameipmi'],
KeyError: 'usernameipmi'

Signed-off-by: Stewart Smith <stewart@linux.vnet.ibm.com>