commit 22ce7b0e8e0d InstallUpstreamKernel.py: add timeout value introduced a timeout value to fix a problem while removing large source files. Unfortunately it introduced following error due to extra paranthesis
Traceback (most recent call last):
  File "./op-test", line 37, in <module>
    from testcases import InstallUpstreamKernel
  File "/home/jenkins/workspace/UpLiKeROPO/testcases/InstallUpstreamKernel.py", line 93
    (linux_path, linux_path), timeout=120))
                                          ^
SyntaxError: invalid syntax

This patch fixes the issue.

Signed-off-by: Sachin Sant <sachinp@linux.vnet.ibm.com>